name: Python Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-quality-checks:
    # Use the latest stable Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up a specific Python environment for consistency
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install linting and formatting tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      # Step 4: Check if code is formatted with Black
      - name: Check formatting with Black
        run: black --check .

      # Step 5: Run Ruff to find potential errors
      - name: Lint with Ruff
        run: ruff check .